### ISSUE TITLE
Vyhladavanie

### ISSUE THREAD

**Issue by Ciksa** [skyjet18/enigma2-plugin-extensions-csfdlite#2]
Skusmo som si nainstaloval verziu 1.2 a nejako sa mi to vyhladavanie nepozdavalo. Tak som to letmo porovnal s full verziou 16.0 a vysledok je ze full verzia hned program nasla a zobrazila info kdezto lite...
![sarkan](https://user-images.githubusercontent.com/44697180/150981582-b7527639-15ae-4f3f-a1e8-9c59f427d1a6.jpg)
![sarkan2](https://user-images.githubusercontent.com/44697180/150981586-ce9c3e1a-7260-4e7d-818c-75a285081526.jpg)
![strach](https://user-images.githubusercontent.com/44697180/150981590-40d424bc-724c-481f-9bad-538e2fc6f7f7.jpg)
![strach2](https://user-images.githubusercontent.com/44697180/150981594-494c3e47-15f8-41fd-9cb3-0ab2fdb3b151.jpg)

**Comment by skyjet18** [comment]
Výsledky vracia csfd. "Veľká" verzia to hľadá cez android api a lite to hľadá priamo na webe. Keď si pozrieš [TU](https://www.csfd.cz/hledat/?q=V+zajetí+strachu+2019) tak poradie výsledkov z lite verzie presne sedí. Ak by sa konkrétne toto hľadanie spravilo bez diakritiky, tak to vráti presnejšie poradie, no pri inom výraze to môže byť naopak. Takže tento stav by som bral ako "vlastnosť" csfd ...

**Comment by Ciksa** [comment]
Nezmenil si skor nieco v algoritme vyhladavania nakolko ked som to teraz porovnal zo svojou starsou verziou tak hned dostanem
![strach3](https://user-images.githubusercontent.com/44697180/150987210-591df414-4f80-4889-a579-b27ef320084e.jpg)
Ale OK. ked nie tak nie.

**Comment by skyjet18** [comment]
Lite verziu nerobím ja. Je možné, že tá staršia verzia porovnáva vo výsledkoch vyhľadávania aj rok vydania a podľa toho sa rozhodne či našla 100% zhodu. Mimochodom toto dobre nefunguje ani vo veľkej verzii - tiež to čaká na komplet prerobenie.
Zatiaľ to nechám otvorené - nech to posúdi, prípadne zavrie mtester270 ...

**Comment by mtester270** [comment]
done
