### ISSUE TITLE
Zobrazenie žánru "genres"

### ISSUE THREAD

**Issue by 005jon** [skyjet18/enigma2-plugin-extensions-csfdlite#5]
Poprosím opraviť zobrazovanie žánru skopíruje celý riadok

`<div class="genres"><a href="/zanry/1-akcni/">Akční</a> / <a href="/zanry/18-krimi/">Krimi</a> / <a href="/zanry/9-komedie/">Komedie</a> / <a href="/zanry/2-drama/">Drama</a></div>`

![genres](https://github.com/skyjet18/enigma2-plugin-extensions-csfdlite/assets/65367517/39ea05f4-e5a9-4c2d-89e0-eef6cd98622f)

**Comment by 005jon** [comment]
![genres](https://github.com/skyjet18/enigma2-plugin-extensions-csfdlite/assets/65367517/39ea05f4-e5a9-4c2d-89e0-eef6cd98622f)

**Comment by skyjet18** [comment]
Opravené vo verzii 1.8
