### ISSUE TITLE
Příliš mnoho informací v EPG u názvu = plugin nenalezne nic

### ISSUE THREAD

**Issue by chocholousek** [skyjet18/enigma2-plugin-extensions-csfdlite#6]
Zdravim! Netusim jestli mohu, ale poprosim take o upravu. Je to vec ktera mne stve uz nejakou dobu. Soudruzi na CT (urcite CT1 CT2 a CT art) udelali upravu v EPG a v nazvu filmu je spousta zbytecnych informaci. Je tomu uz delsi dobu kdyz dam vyhledat info o nejakem filmu nedostanu zadny vysledek. Nezobrazi se ani seznam filmu, vysledek je proste NIC. Coz je trochu problem protoze to se neda jinak obejit nez jit na csfd pres telefon.
![1_0_19_1F43_CA1_3_EB0000_0_0_0_20240120094058](https://github.com/skyjet18/enigma2-plugin-extensions-csfdlite/assets/54640364/076f72b1-f3b9-4ae4-9071-defdecd1e640)
Tohle je pokus o vyhledani Lid versus Larry Flynt, kdyz jdu na csfd a pokusim se vyhledat presne to co mi to pise na obrazku opravdu to nenajde vubec nic, musim retezec zkratit `Lid versus Larry Flynt, People vs. Larry Flynt, The, Velikáni filmu... Woody Harrelson` na `Lid versus Larry Flynt, People vs. Larry Flynt` az pote je nalezen alespon seznam filmu coz tak nejak by uplne stacilo. No snad jsem to popsal srozumitelne.

**Comment by skyjet18** [comment]
Pokiaľ dobre viem, tak takúto somarinu má ČT na Skylinku už dávno. Na ostatných platformách to EPG vyzerá normálne. Vo "veľkom" CSFD to funguje tak ako má. Pre ČT na Skylink je tam výnimka a názov filmu sa špeciálne parsuje aby sa z toho dostal zmysluplný názov. Niečo podobné by bolo potrebné pridať aj sem. No keďže je to "lite" plugin, tak mnoho vecí je tam výrazne jednoduchších a napr. nikde sa tu nerieši z akého kanálu sa info získalo.
A ešte jedna dôležitá vec: O csfdlite sa strará mtester270. Keď tak mu môžeš skúsiť napísať mail. Na mojom github účte to je len preto, aby tie csfd pluginy boli na jednom mieste. Ja osobne sa riešim len "veľký" CSFD. Na to aby som riešil ešte niečo ďalšie už naozaj nemám priestor. Posledná oprava bola výnimka, keďže bolo potrebné zmeniť len jeden riadok ...

**Comment by chocholousek** [comment]
Zdravím, ano máš pravdu omlouvám se, ser nato...
